version: '3'
services:
  db:
    hostname: primary
    image: sogis/wmts-db:latest
    environment:
      PG_DATABASE: wmts
      PG_LOCALE: de_CH.UTF-8
      PG_PRIMARY_PORT: 5432
      PG_MODE: primary
      PG_USER: admin
      PG_PASSWORD: admin
      PG_PRIMARY_USER: repl
      PG_PRIMARY_PASSWORD: repl
      PG_ROOT_PASSWORD: secret
      PG_WRITE_USER: gretl
      PG_WRITE_PASSWORD: gretl
      PG_READ_USER: ogc_server
      PG_READ_PASSWORD: ogc_server
    ports:
      - "54321:5432"
    volumes:
       - ~/pgdata-wmts:/pgdata:delegated
    restart: always
  wms:
    image: sogis/wmts-wms:latest
    environment:
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: 4
      QGIS_FCGI_MAX_PROCESSES: 4
      QGIS_FCGI_MIN_PROCESSES: 4
      QGIS_SERVER_LOG_LEVEL: 0
    ports:
      - 8083:80
    depends_on:
      - db
    restart: always
  wmts:
    image: sogis/wmts-service:latest
    ports:
      - 8281:8080
    depends_on:
      - wms
    restart: always
